beoplay_join_experience:
  name: "Join Experience"
  description: "Join an ongoing playback experience. E.g., the speaker starts playback of a CD already playing on another device."
  fields:
    entity_id:
      name: "B&O Media player"
      description: "A media player Entity ID."
      example: "media_player.my_chromecast"
beoplay_leave_experience:
  name: "Leave Experience"
  description: "Leave the current playback experience."
  fields:
    entity_id:
      name: "B&O Media player"
      description: "A media player Entity ID."
      example: "media_player.my_chromecast"
beoplay_add_media_to_queue:
  name: "Add to playback Queue"
  description: "Add media to the current playback queue. This is untested. Please report back if it works."
  fields:
    entity_id:
      name: "B&O Media player"
      description: "A media player Entity ID."
      example: "media_player.my_beosound"
    url:
      name: "Media URL"
      description: "A URL to add to the playback queue. Must be reachable from the speaker."
      example: "http://192.168.1.1/DLNAfile.mp3"